imports:
  - custom_env.yaml

experiment:
  name: "rmax_custom_grid_5x6"
  seed: 42
  total_episodes: 20000
  max_steps_per_episode: 150
  eval_episodes: 100
  results_dir: "results"

algorithm:
  class_path: 'algorithms.rmax.RMaxAgent'
  save_model_filename: "rmax_custom_grid_final.pkl"
  hyperparameters:
    gamma: 0.99
    m: 10
    R_max: 1.0
    planning_iterations: 50
    planning_tolerance: 1e-3
