imports:
  - custom_env.yaml

experiment:
  name: "qlearn_custom_grid_5x5_ms1"
  seed: 42
  total_episodes: 10000
  max_steps_per_episode: 100
  eval_episodes: 100
  results_dir: "results"

algorithm:
  class_path: 'algorithms.rmax.RMaxAgent'
  save_model_filename: "rmax_custom_grid_final.pkl"
  hyperparameters:
    gamma: 0.99
    alpha: 0.1
    epsilon_start: 1.0
    epsilon_min: 0.05
    epsilon_decay: 0.999